//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Gimpel3D.rc
//
#define IDC_YES                         3
#define IDC_NOPE                        4
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_GIMPEL3D_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDD_GETTEXT_DLG                 129
#define IDD_ROTOSCOPE_DLG               130
#define IDR_MAIN_MENU                   131
#define IDD_DEPTH_EDIT_DLG              132
#define IDD_STEREO_SETTINGS_DLG         133
#define IDD_PLANAR_PROJECTION_DLG       134
#define IDD_CONTOUR_EXTRUSION_DIALOG    135
#define IDD_DEPTH_SLIDER                136
#define IDD_SCALE_SLIDER                137
#define IDD_SHOT_SEQUENCE_DLG           138
#define IDD_RELIEF_MAP_DLG              139
#define IDD_RENDERING_OPTIONS_DLG       140
#define IDR_FILE_TOOLBAR                141
#define IDD_FRAME_COUNTER_DLG           143
#define IDD_PROJECTION_SETTINGS_DLG     144
#define IDD_LAYERS_DLG                  145
#define IDD_FRAMES_DLG                  146
#define IDD_TIMELINE_SLIDER_DLG         147
#define IDD_LIST_SELECT_DLG             148
#define IDD_EXPORT_OPTIONS              149
#define IDD_IMPORT_OPTIONS              150
#define IDD_ALIGNMENT_OPTIONS           151
#define IDD_3D_FRAME_DLG                153
#define IDD_3D_VIEW_OPTIONS             154
#define IDD_INFO_BAR_DLG                155
#define IDB_LOGO                        156
#define IDD_TRACK_OUTLINE_DLG           157
#define IDD_SHIFT_EDGES                 158
#define IDD_2D_VIEW_OPTIONS             159
#define IDB_START_BUTTONU               165
#define IDB_STOP_BUTTONU                166
#define IDB_PAUSE_BUTTONU               167
#define IDB_PAUSE_BUTTOND               168
#define IDB_STOP_BUTTOND                169
#define IDB_START_BUTTOND               170
#define IDB_PAUSE_BUTTONX               171
#define IDB_STOP_BUTTONX                172
#define IDB_START_BUTTONX               173
#define IDD_GAP_FILL_DLG                176
#define IDD_GEOMETRY_TOOL_DLG           177
#define IDD_AUTO_SEGMENT_DLG            178
#define IDD_TOOLS_REFERENCE             179
#define IDD_HTML_VIEWER_DLG             181
#define IDD_HELP_DLG                    183
#define IDD_PERSPECTIVE_DLG             185
#define IDD_SHAPES_DLG                  186
#define IDD_ANCHOR_POINTS_DLG           187
#define IDD_VIRTUAL_SET                 188
#define IDD_IMPORT_LIST_DLG             189
#define IDD_FEATURE_POINTS_DLG          190
#define IDB_SKIN                        191
#define IDD_SKIN_FRAME                  192
#define IDD_TOOLBAR_DLG                 193
#define IDD_LINK_POINTS_DLG             197
#define IDB_ANAGLYPH_BUTTON             201
#define IDB_FULLSCREEN_BUTTON           202
#define IDD_TOOLTRAY_DLG                203
#define IDD_COLOR_DLG                   204
#define IDD_PREVIEW_DLG                 205
#define IDD_SKIN_MESSAGEBOX             206
#define IDD_VIRTUAL_CAMERA_DLG          207
#define IDB_GRID_BUTTON                 208
#define IDB_CAMERA_BUTTON               209
#define IDD_PAINT_TOOL_DLG              210
#define IDD_PLUGINS                     212
#define IDD_TOUCH_UPS_DLG               213
#define IDD_HALO_TOOL_DLG               214
#define IDB_GIMPEL3DLOGO                216
#define IDC_ANTIALIAS_HARD_EDGES        1000
#define IDC_FULL_SCREEN_3D              1001
#define IDC_FULL_SCREEN_2D              1002
#define IDC_LEFT_VIEW                   1003
#define IDC_LAYERS_LABEL                1004
#define IDC_FRAMES_LABEL                1005
#define IDC_BOTTOM_VIEW                 1006
#define IDC_SPLIT_SCREEN                1007
#define IDC_WIDE_SCREEN_3D              1008
#define IDC_SHOW_OLD_GUIS               1009
#define IDC_EYE_SEPARATION              1010
#define IDC_EDIT_HINT                   1011
#define IDC_RECALC_CENTER               1012
#define IDC_START                       1013
#define IDC_UPDATE_LAYER_DATA           1014
#define IDC_GAP_LIST                    1015
#define IDC_REFRESH_LIST                1016
#define IDC_BLEND_FRAME_LIST            1017
#define IDC_GAP_THRESHOLD_SLIDER        1018
#define IDC_INTERPOLATE_FILL            1019
#define IDC_DUPLICATE_FILL              1020
#define IDC_BLEND_FILL                  1021
#define IDC_BROWSE_BLEND_IMAGE          1022
#define IDC_GAPFILL_LEFT                1023
#define IDC_GAPFILL_RIGHT               1024
#define IDC_GAPFILL_ANAGLYPH            1025
#define IDC_GAPFILL_SAVE                1026
#define IDC_CLEAR_GAP_INFO              1027
#define IDC_HIGHLIGHT_GAPS              1028
#define IDC_NO_FILL                     1029
#define IDC_NO_FILL_ALL                 1030
#define IDC_INTERPOLATE_ALL             1031
#define IDC_FLAT_PLANE                  1032
#define IDC_EXPORT_LEFT_GAPMASK         1032
#define IDC_SPHERE                      1033
#define IDC_EXPORT_LEFT_FILLED_IMAGE    1033
#define IDC_CYLINDER                    1034
#define IDC_EXPORT_RIGHT_GAPMASK        1034
#define IDC_BOX                         1035
#define IDC_EXPORT_RIGHT_FILLED_IMAGE   1035
#define IDC_CONE                        1036
#define IDC_EXPORT_FILLED_ANAGLYPH      1036
#define IDC_MODEL                       1037
#define IDC_EXPORT_FILLED_STEREO        1037
#define IDC_BROWSE_MODEL                1038
#define IDC_PROJECT_TO_MODEL            1039
#define IDC_RESTORE_ORIGINAL_IMAGE      1040
#define IDC_LINK_POINTS                 1040
#define IDC_DARKNESS_THRESHOLD_SLIDER   1041
#define IDC_OUTLINES_ONLY               1042
#define IDC_RENDER_BACKGROUND_BLEND_IMAGE 1043
#define IDC_CLEAR_BLEND_PIXELS          1044
#define IDC_INVERT_GEOMETRY             1045
#define IDC_COLOR_THRESHOLD_SLIDER      1046
#define IDC_HTML_WINDOW                 1049
#define IDC_SWITCH_SIDES                1050
#define IDC_HTML_VIEW_CONTROL           1051
#define IDC_HELP_TOC                    1053
#define IDC_BACK                        1054
#define IDC_ANCHOR_POINTS_LIST          1055
#define IDC_TRAPEZOID                   1056
#define IDC_ANGLE_AT_CORNER             1057
#define IDC_FOV_EDIT                    1058
#define IDC_SET_PERSPECTIVE_FOV         1059
#define IDC_UPDATE_GRID                 1060
#define IDC_PERSPECTIVE_ANGLE           1061
#define IDC_APPLY_PERSPECTIVE           1062
#define IDC_VANISHING_POINT             1063
#define IDC_ALIGN_PERSPECTIVE_FORWARD   1064
#define IDC_ALIGN_PERSPECTIVE_BACK      1065
#define IDC_ALIGN_PERSPECTIVE_LEFT      1066
#define IDC_ALIGN_PERSPECTIVE_RIGHT     1067
#define IDC_ALIGN_PERSPECTIVE_ALL       1068
#define IDC_MODIFY_GRID                 1069
#define IDC_MODIFY_GRID_TO_WALL         1070
#define IDC_GENERATE_CONTRAST_MAP       1071
#define IDC_SET_DEFAULT_ALIGNMENT       1071
#define IDC_INCREASE_SEARCH_RANGE       1072
#define IDC_ANCHOR_RANGE                1073
#define IDC_ANCHOR_RANGE_SLIDER         1074
#define IDC_CLICK_TO_ADD_POINTS         1075
#define IDC_CLEAR_ANCHOR_POINTS         1076
#define IDC_VIEW_MODEL                  1076
#define IDC_CLICK_TO_DELETE_POINTS      1077
#define IDC_CLICK_TO_MOVE_POINTS        1078
#define IDC_TRACK_FEATURE_POINTS        1079
#define IDC_VIEW_SCENE                  1079
#define IDC_COPY_ANCHOR_POINTS          1079
#define IDC_LINEAR_FALLOFF              1080
#define IDC_SHOW_VECTORS                1080
#define IDC_STATIC_LAYERS_LIST          1081
#define IDC_APPLY_SAVED_ANCHOR_POINTS   1081
#define IDC_DYNAMIC_LAYERS_LIST         1082
#define IDC_CLEAR_SAVED_ANCHOR_POINTS   1082
#define IDC_SAVE_SCENE_FRAMEWORK        1083
#define IDC_ATTACH_ANCHOR_POINT_TO_SELECTED_FEATURE_POINT 1083
#define IDC_LOAD_SCENE_FRAMEWORK        1084
#define IDC_REMOVE_ANCHOR_POINT_FROM_SELECTED_FEATURE_POINT 1084
#define IDC_TRACK_TO_NEXT_FRAME         1085
#define IDC_REMOVE_ALL_ANCHOR_POINTS    1085
#define IDC_CLEAR_ALL_POINTS            1086
#define IDC_CLEAR_ALL_FEATURE_POINT_KEYFRAMES 1087
#define IDC_RENDER_SCENE_FRAMEWORK      1088
#define IDC_KEYFRAME_ALL_POINTS_FOR_THIS_FRAME 1088
#define IDC_START_FEATURE_POINT_OUTLINE 1089
#define IDC_CANCEL_FEATURE_POINT_OUTLINE 1090
#define IDC_FINISH_FEATURE_POINT_OUTLINE 1091
#define IDC_FEATURE_POINT_LIST          1092
#define IDC_DONE                        1093
#define IDC_CLEAR_ALL_KEYFRAMES_FOR_THIS_POINT 1093
#define IDC_CANCEL                      1094
#define IDC_RENDER_GRID                 1095
#define IDC_KEYFRAME_FEATURE_POINTS     1096
#define IDC_FEATURE_POINT_OUTLINE_LIST  1097
#define IDC_STATIC1                     1098
#define IDC_KEYFRAME_SELECTED_FEATURE_POINT 1098
#define IDC_STATIC2                     1099
#define IDC_STATIC3                     1100
#define IDC_STATIC4                     1101
#define IDC_STATIC5                     1102
#define IDC_STATIC6                     1103
#define IDC_STATIC7                     1104
#define IDC_STATIC8                     1105
#define IDC_STATIC9                     1106
#define IDC_STATIC10                    1107
#define IDC_STATIC11                    1108
#define IDC_STATIC12                    1109
#define IDC_STATIC13                    1110
#define IDC_VIEW_UP                     1111
#define IDC_CLOSE_BUTTON                1111
#define IDC_CENTER_HORIZONTAL_ROTATION  1112
#define IDC_NEW                         1112
#define IDC_MINIMIZE_BUTTON             1112
#define IDC_VIEW_DOWN                   1113
#define IDC_SAVE                        1113
#define IDC_GENERATE_TRACKING_INFO_FOR_SELECTION 1114
#define IDC_LOAD                        1114
#define IDC_VIEW_LEFT                   1115
#define IDC_IMPORT_DATA                 1115
#define IDC_CREATE_LAYERS_FROM_TRACKING_INFO 1116
#define IDC_EXPORT_DATA                 1116
#define IDC_VIEW_RIGHT                  1117
#define IDC_SPLASH                      1117
#define IDC_FULLSCREEN_2D               1117
#define IDC_CREATE_LAYERS_AND_ADVANCE_FRAME 1118
#define IDC_SPLITSCREEN                 1118
#define IDC_ALIGN_MODEL                 1118
#define IDC_EXPAND_OUTLINES             1119
#define IDC_FULLSCREEN_3D               1119
#define IDC_ALIGN_MODEL2                1119
#define IDC_ZOOM_IN                     1120
#define IDC_ALIGN_MODEL3                1120
#define IDC_ZOOM_OUT                    1121
#define IDC_ALIGN_MODEL4                1121
#define IDC_REPLACE_LAYERS_FROM_TRACKING_INFO 1122
#define IDC_SHIFT_BACK                  1122
#define IDC_FIND_START_ALIGNMENT        1122
#define IDC_CLEAR_LINK_POINTS           1123
#define IDC_SHIFT_FORWARD               1123
#define IDC_SAVE_LINK_POINTS            1124
#define IDC_RED1                        1124
#define IDC_LOCK_LEFT                   1125
#define IDC_RELOAD_LINK_POINTS          1125
#define IDC_GREEN1                      1125
#define IDC_LOCK_RIGHT                  1126
#define IDC_LINK_SELECTED_POINTS        1126
#define IDC_BLUE1                       1126
#define IDC_LOCK_CENTER                 1127
#define IDC_CLEAR_LINKS                 1127
#define IDC_MIX_SLIDER                  1127
#define IDC_LOCK_TOP                    1128
#define IDC_RED2                        1128
#define IDC_SAVE_LINKS                  1128
#define IDC_LOCK_BOTTOM                 1129
#define IDC_UNLINK_SELECTED_POINTS      1129
#define IDC_GREEN2                      1129
#define IDC_SET_PUFF_RANGE              1130
#define IDC_BLUE2                       1130
#define IDC_CENTER_PUFF_RANGE           1131
#define IDC_NORMAL_BUTTON               1131
#define IDC_PUFF_RANGE_SLIDER           1132
#define IDC_PUSHED_BUTTON               1132
#define IDC_SPHERICAL_EXTRUSION         1133
#define IDC_DISABLED_BUTTON             1133
#define IDC_LINEAR_EXTRUSION            1134
#define IDC_APPLY_COLORS                1134
#define IDC_INCREASE_EXTRUSION_ANGLE    1135
#define IDC_CHECKBOX                    1135
#define IDC_SET_EXTRUSION_ANGLE         1136
#define IDC_LISTBOX                     1136
#define IDC_SET_PUFF_SCALE              1137
#define IDC_APPLY_DEFAULT_COLORS        1137
#define IDC_APPLY_CONTOUR               1138
#define IDC_PRECACHE_ALL_FRAMES         1138
#define IDC_STATUS                      1139
#define IDC_PRECACHE_CURRENT_FRAMES     1139
#define IDC_SELECTION_STATUS            1140
#define IDC_DIRECTIONAL_EXTRUSION       1141
#define IDC_DISK_SPACE                  1141
#define IDC_SPECKLE_SKIP                1142
#define IDC_RESTRICT_RANGE              1142
#define IDC_SET_SPECKLE_SKIP            1143
#define IDC_PLAY_STOP                   1143
#define IDC_SET_ALL_VISIBLE             1144
#define IDC_LOOP                        1144
#define IDC_SET_ALL_INVISIBLE           1145
#define IDC_CURRENT_FRAME               1145
#define IDC_DEPTH_SLIDER                1146
#define IDC_DELETE_FRAME_DATA           1146
#define IDC_SAVED_ORIENTATION           1146
#define IDC_DEPTH                       1147
#define IDC_OK                          1147
#define IDC_RECALC_SPACE                1147
#define IDC_SET_DEPTH                   1148
#define IDC_SLIDER_RANGE                1149
#define IDC_FRAMES_LIST                 1149
#define IDC_SET_SLIDER_RANGE            1150
#define IDC_SCALE                       1151
#define IDC_SELECT_TRACKING_FEATURE_POINTS 1151
#define IDC_SET_SCALE                   1152
#define IDC_UNSELECT_TRACKING_FEATURE_POINTS 1152
#define IDC_SCALE_SLIDER                1153
#define IDC_CLEAR_TRACKED_FEATURE_POINTS 1153
#define IDC_BIAS_SLIDER                 1154
#define IDC_RENDER_CAMERA_VECTORS_TO_POINTS 1154
#define IDC_ADJUSTABLE_FOV              1154
#define IDC_SHOT_LIST                   1155
#define IDC_RENDER_CAMERA_PATH          1155
#define IDC_SET_BIAS                    1156
#define IDC_SET_CURRENT_FRAME_AS_REFERENCE 1156
#define IDC_RANDOM_NOISE                1157
#define IDC_GENERATE_RELATIVE_CAMERA_PATH 1157
#define IDC_COLOR_DIFFERENCE            1158
#define IDC_RESET_VIRTUAL_CAMERA_INFO   1158
#define IDC_GENERATE_RELATIVE_CAMERA_POSITION 1159
#define IDC_TRACK_YAW                   1160
#define IDC_SELECT_CONCAVE_COLOR        1161
#define IDC_TRACK_PITCH                 1161
#define IDC_SELECT_CONVEX_COLOR         1162
#define IDC_RENDER_CAMERA_DIRECTION     1162
#define IDC_SPLIT_LAYER                 1163
#define IDC_SMOOTH_CAMERA_PATH          1163
#define IDC_SELECT_ALL                  1164
#define IDC_SMOOTH_CAMERA_STEPS         1164
#define IDC_SELECT_NONE                 1165
#define IDC_RENDER_PAINT_TOOL           1165
#define IDC_TILING                      1166
#define IDC_RENDER_FRAME_IMAGE          1166
#define IDC_SET_TILING                  1167
#define IDC_RENDER_GRAYSCALE_IMAGE      1167
#define IDC_TILING_SLIDER_RANGE         1168
#define IDC_RENDER_LAYERMASK_IMAGE      1168
#define IDC_SET_TILING_SLIDER_RANGE     1169
#define IDC_GRAYSCALE_NEAR              1169
#define IDC_SET_SCALE_SLIDER_RANGE      1170
#define IDC_GRAYSCALE_FAR               1170
#define IDC_SCALE_SLIDER_RANGE          1171
#define IDC_RESET_GRAYSCALE_IMAGE       1171
#define IDC_CONTRAST_SLIDER             1172
#define IDC_PLUGIN_LIST                 1172
#define IDC_CONTRAST                    1173
#define IDC_OPEN_PLUGIN                 1173
#define IDC_SET_CONTRAST                1174
#define IDC_CLOSE_PLUGINS               1174
#define IDC_ACTIVATE                    1174
#define IDC_CONTRAST_SLIDER_RANGE       1175
#define IDC_RELOAD_PLUGIN               1175
#define IDC_DEACTIVATE                  1175
#define IDC_SET_CONTRAST_SLIDER_RANGE   1176
#define IDC_UNLOAD_PLUGIN               1176
#define IDC_ALLOW_SCALE_X               1176
#define IDC_CHANGE_IMAGE                1177
#define IDC_RELOAD_ALL_PLUGINS          1177
#define IDC_ALLOW_SCALE_Y               1177
#define IDC_IMAGE_FILE                  1178
#define IDC_UNLOAD_ALL_PLUGIN           1178
#define IDC_ALLOW_SCALE_Z               1178
#define IDC_CONCAVE_COLOR_BUTTON        1179
#define IDC_BROWSE_FOR_PLUGIN           1179
#define IDC_ALLOW_FREE_MOTION           1179
#define IDC_CONVEX_COLOR_BUTTON         1180
#define IDC_ALLOW_ROTATE_X              1180
#define IDC_RESET_BIAS                  1181
#define IDC_ALLOW_ROTATE_Y              1181
#define IDC_PICK_CONCAVE_COLOR          1182
#define IDC_ALLOW_ROTATE_Z              1182
#define IDC_FLY_SPEED_SLIDER            1183
#define IDC_ALLOW_MOVE_X                1183
#define IDC_BRIGHTNESS_ONLY             1184
#define IDC_ALLOW_MOVE_Y                1184
#define IDC_CLOSING_STATEMENT           1184
#define IDC_SMOOTH_TRANSITION           1185
#define IDC_ALLOW_MOVE_Z                1185
#define IDC_CONTRAST_LABEL              1186
#define IDC_TOUCH_UP_LIST               1186
#define IDC_CONTRAST_SLIDER_RANGE_LABEL 1187
#define IDC_CLEAR_ALL_EDITS             1187
#define IDC_TILING_LABEL                1188
#define IDC_CLEAR_SELECTED_EDIT         1188
#define IDC_GENERATE_HALO_MASK          1188
#define IDC_IMAGE_LABEL                 1189
#define IDC_UNDO_EDIT                   1189
#define IDC_HALO_PIXEL_RANGE            1189
#define IDC_TILING_SLIDER_RANGE_LABEL   1190
#define IDC_REDO_EDIT                   1190
#define IDC_HALO_RANGE_SLIDER           1190
#define IDC_CONCAVE_COLOR_LABEL         1191
#define IDC_REMEMBER_ALL_EDITS          1191
#define IDC_FIND_HALO_OUTLINE           1191
#define IDC_DIFFERENCE_BIAS_LABEL       1192
#define IDC_APPLY_STORED_EDITS          1192
#define IDC_RENDER_2D_HALO              1192
#define IDC_CONVEX_COLOR_LABEL          1193
#define IDC_REFRESH_AND_REAPPLY         1193
#define IDC_BLEND_HALO_WITH_BACKGROUND  1193
#define IDC_MFC_SELECT_CONCAVE_COLOR    1194
#define IDC_REFRESH_AND_DONT_APPLY      1194
#define IDC_UPDATE_HALO_GEOMETRY        1194
#define IDC_MFC_SELECT_CONVEX_COLOR     1195
#define IDC_APPLY_SELECTED              1195
#define IDC_RENDER_3D_HALO              1195
#define IDC_SCALE_LABEL                 1196
#define IDC_RENDER_HALO_ALPHAMASK       1196
#define IDC_SLIDER_RANGE_LABEL          1197
#define IDC_GENERATE_DEFAULT_HALOS      1197
#define IDC_FLIP_SCALE_SLIDER_RANGE     1198
#define IDC_SORT_HALOS_MODIFY_FRAME     1198
#define IDC_AUTO_APPLY_TO_OTHER_FRAMES  1198
#define IDC_DELETE_HALO_MASK            1199
#define IDC_HORIZONTAL_LINES            1199
#define IDC_SAVE_HALO_MASK              1200
#define IDC_UPDATE_ALL_HALO_GEOMETRY    1201
#define IDC_DELETE_ALL_HALO_MASKS       1202
#define IDC_GS                          1203
#define IDC_SAVE_HALO_INFO              1203
#define IDC_CA                          1204
#define IDC_APPLY_SAVED_HALO_INFO       1204
#define IDC_OA                          1205
#define IDC_CLEAR_SAVED_HALO_INFO       1205
#define IDC_LS                          1206
#define IDC_AUTO_LOAD_HALOS             1206
#define IDC_SHIFT_LEFT_OUT              1207
#define IDC_LOAD_HALOS_FOR_FRAME        1207
#define IDC_SHIFT_LEFT_IN               1208
#define IDC_SHIFT_TOP_DOWN              1209
#define IDC_SHIFT_TOP_UP                1210
#define IDC_SHIFT_RIGHT_IN              1211
#define IDC_SHIFT_RIGHT_OUT             1212
#define IDC_SHIFT_BOTTOM_DOWN           1213
#define IDC_SHIFT_BOTTOM_UP             1214
#define IDC_FLAT_PROJECTION             1215
#define IDC_FLIP_IMAGES                 1216
#define IDC_TIMELINE_SLIDER             1217
#define IDC_SELECT_LIST                 1219
#define IDC_CLICK_SELECT                1220
#define IDC_UPDATE_3D_DATA              1221
#define IDC_FLIP_DEPTH                  1222
#define IDC_FLIP_LAYERS                 1223
#define IDC_FLIP_IMAGES2                1224
#define IDC_START_EXPORT                1225
#define IDC_FLIP_LAYERS2                1226
#define IDC_FLIP_GRAYSCALE_VERTICAL     1227
#define IDC_FLIP_GRAYSCALE_HORIZONTAL   1228
#define IDC_KEYFRAME_STEREO             1229
#define IDC_APPLY_STEREO_SETTINGS_TO_ALL 1230
#define IDC_RENDER_FOCAL_PLANE          1231
#define IDC_IMPORT_IMAGES               1232
#define IDC_IMAGES_PATH                 1233
#define IDC_BROWSE_IMAGES_PATH          1234
#define IDC_LAYERMASKS_PATH             1235
#define IDC_BROWSE_LAYERMASKS_PATH      1236
#define IDC_IMPORT_LAYERMASKS           1237
#define IDC_DEPTHMASKS_PATH             1238
#define IDC_BROWSE_DEPTHMASKS_PATH      1239
#define IDC_IMPORT_DEPTHMASKS           1240
#define IDC_APPLY_IMAGE_FILTER          1241
#define IDC_TOTAL_ERROR                 1242
#define IDC_START_AUTO_ALIGNMENT        1243
#define IDC_FORM_FIT_TO_SURROUNDINGS    1244
#define IDC_ALIGNMENT_ANGLE             1245
#define IDC_IDENTIFY_EDGE_PIXELS        1246
#define IDC_ALIGN_DEPTH                 1247
#define IDC_ALIGN_XROT                  1248
#define IDC_ALIGN_YROT                  1249
#define IDC_ALIGN_ANGLE                 1251
#define IDC_PLUS_ANGLE_X                1252
#define IDC_MINUS_ANGLE_X               1253
#define IDC_PLUS_ANGLE_Y                1254
#define IDC_SMOOTH_OUTLINES             1255
#define IDC_MINUS_ANGLE_Y               1256
#define IDC_APPLY_POST_BLEND            1257
#define IDC_ALIGN_ALL                   1258
#define IDC_POST_BLEND_PASSES           1259
#define IDC_ALIGN_PRIMITIVE             1259
#define IDC_INC_POST_BLEND_PASSES       1260
#define IDC_APPLY_ALIGNMENT_TO_ALL_FRAMES 1260
#define IDC_ALIGN_PARALLEL              1261
#define IDC_DEC_POST_BLEND_PASSES       1262
#define IDC_EXPAND_CONTRACT_AMOUNT      1263
#define IDC_START_EVALUATION            1264
#define IDC_EXIT                        1265
#define IDC_IMPORT                      1266
#define IDC_EXPORT                      1267
#define IDC_REPLACE_IMAGE               1268
#define IDC_IMPORT_DEPTH_MASK           1269
#define IDC_EXPORT_LAYER_MASK           1270
#define IDC_EXPORT_DEPTH_MASK           1271
#define ID_MENUITEM32783                1272
#define ID_MENUITEM32784                1273
#define IDC_IMPORT_STEREO_SETTINGS      1274
#define IDC_FLIP_IMAGE_VERTICAL         1275
#define IDC_FLIP_IMAGE_HORIZONTAL       1276
#define IDC_FLIP_LAYERS_VERTICAL        1277
#define IDC_FLIP_LAYERS_HORIZONTAL      1278
#define IDC_FLIP_DEPTH_MASK_VERTICAL    1279
#define IDC_FLIP_DEPTH_MASK_HORIZONTAL  1280
#define IDC_FLIP_DEPTH_MASK_DEPTH       1281
#define IDC_FLIP_RED_BLUE               1282
#define IDC_SINGLE_MONITOR              1283
#define IDC_DUAL_MONITOR                1284
#define IDC_SWAP_MONITORS               1285
#define ID_VIEWS                        1286
#define IDC_STEREO_SETTINGS             1287
#define IDC_IMPORT_LAYERS               1288
#define IDC_3D_VIEW_OPTIONS             1289
#define IDC_2D_VIEW_OPTIONS             1290
#define IDC_LAYER_ALL_FRAMES            1291
#define IDC_AUTO_ALIGNMENT              1292
#define IDC_LAYER_SINGLE_FRAME          1293
#define IDC_HORIZONTAL_ROTATION         1294
#define IDC_KEY_COMMANDS                1295
#define IDC_SHIFT_EDGES                 1297
#define IDC_TOOLS_REFERENCE             1298
#define IDC_ABOUT_G3D                   1299
#define IDC_INTRODUCTION                1300
#define IDC_OPEN_POST_EDITOR            1302
#define IDC_OPEN_GAPFILL_EDITOR         1303
#define IDC_APPLY_GEOMETRY              1304
#define IDC_AUTO_SEGMENT_IMAGE          1305
#define IDC_SHOW_HELP                   1318
#define IDC_GET_PERSPECTIVE_PROJECTION  1319
#define IDC_OPEN_SHAPES_TOOL            1320
#define IDC_OPEN_VIRTUAL_SET_TOOL       1321
#define IDC_OPEN_ANCHOR_POINTS_TOOL     1322
#define IDC_FEATURE_POINTS_TOOL         1323
#define IDC_EYE_SEPARATION_SLIDER       1324
#define IDC_RIGHT_VIEW                  1325
#define IDC_TOP_VIEW                    1326
#define IDC_FOCAL_LENGTH                1327
#define IDC_EDGE_FADE                   1328
#define IDC_HORIZONTAL_POSITION         1329
#define IDC_FOCAL_LENGTH_SLIDER         1330
#define IDC_STOP                        1331
#define IDC_MAX_EYE_SEPARATION          1332
#define IDC_PAUSE                       1333
#define IDC_HORIZONTAL_POSITION_SLIDER  1334
#define IDC_STEP_BACK                   1334
#define IDC_MAX_FOCAL_LENGTH            1335
#define IDC_STEP_FORWARD                1335
#define IDC_VERTICAL_POSITION_SLIDER    1336
#define IDC_STEP_BACK2                  1336
#define IDC_MIN_EYE_SEPARATION          1337
#define IDC_STEP_FORWARD2               1337
#define IDC_VERTICAL_POSITION           1338
#define IDC_STEP_BACK3                  1338
#define IDC_MIN_FOCAL_LENGTH            1339
#define IDC_STEP_FORWARD3               1339
#define IDC_DEPTH_POSITION_SLIDER       1340
#define IDC_DEPTH_POSITION              1341
#define IDC_SAVE_STEREO_IMAGE           1342
#define IDC_SAVE_LEFT_IMAGE             1343
#define IDC_SAVE_RIGHT_IMAGE            1344
#define IDC_DUPLICATE_ALL               1345
#define IDC_DEPTH_SCALE_SLIDER          1346
#define IDC_SAVE_ANAGLYPH               1347
#define IDC_BLEND_IMAGE_ALL             1348
#define IDC_SAVE_STEREOGRAM             1349
#define IDC_FINALIZE_GAP_FILL           1350
#define IDC_RESET_DEPTH_SCALE           1351
#define IDC_RENDER_GHOST_BLEND_IMAGE    1352
#define IDC_DEPTH_SCALE_OFFSET_SLIDER   1353
#define IDC_APPLY_BLEND_PIXELS          1354
#define IDC_RESET_DEPTH_SCALE_OFFSET    1355
#define IDC_ALIGN_BLEND_IMAGE           1356
#define IDC_MAX_DEPTH_SCALE             1357
#define IDC_FINALIZE_GAP_PIXELS         1358
#define IDC_MIN_DEPTH_SCALE             1359
#define IDC_PREVIEW_BLENDED_GAP_FILL    1360
#define IDC_USE_CARTOON_EDGE_DETECTION  1361
#define IDC_MAX_DEPTH_SCALE_OFFSET      1362
#define IDC_MIN_DEPTH_SCALE_OFFSET      1363
#define IDC_SHOW_GAPS                   1364
#define IDC_EDGE_FADE_SLIDER            1365
#define IDC_PREVIEW_FILLED_ANAGLYPH     1366
#define IDC_RESET_EDGE_FADE             1367
#define IDC_ANAGLYPH                    1368
#define IDC_PREVIEW_SEGMENTS            1369
#define IDC_GRID_BUTTON                 1369
#define IDC_SET_EXP_DEPTH_SCALE         1370
#define IDC_CAMERA_BUTTON               1370
#define IDC_RESET_PREVIEW               1371
#define IDC_SHOW_GEOMETRY               1372
#define IDC_FINALIZE_SEGMENTS           1373
#define IDC_SHOW_GEOMETRY_WIREFRAME     1374
#define IDC_HIDE_LISTS                  1375
#define IDC_LAYERS_LIST                 1376
#define IDC_UNSELECT_LAYERS             1377
#define IDC_FORWARD                     1378
#define IDC_PARALLEL_LINES              1379
#define IDC_DELETE_LAYERS               1380
#define IDC_RECTANGLE                   1380
#define IDC_MERGE_LAYERS                1381
#define IDC_FREEZE_LAYER                1382
#define IDC_OUTLINE_LAYER               1383
#define IDC_SPECKLE_LAYER               1384
#define IDC_LAYER_VISIBLE               1385
#define IDC_LAYER_KEYFRAME              1386
#define IDC_EVAPORATE_LAYERS            1387
#define IDC_SEARCH_RANGE                1388
#define IDC_INCREASE_DEPTH              1389
#define IDC_DECREASE_DEPTH              1390
#define IDC_INCREASE_SCALE              1391
#define IDC_SET_SEARCH_RANGE            1392
#define IDC_DECREASE_SCALE              1393
#define IDC_DECREASE_SEARCH_RANGE       1394
#define IDC_RENAME_SELECTION            1395
#define IDC_UPDATE_AFFECTED_LAYERS      1396
#define IDC_PUFF_SCALE                  1397
#define IDC_STRETCH_FALLOFF             1398
#define IDC_PUFF_RANGE                  1399
#define IDC_CURVE_FALLOFF               1400
#define IDC_EXTRUSION_ANGLE             1401
#define IDC_UPDATE_ANCHOR_POINTS_IN_REALTIME 1402
#define IDC_EDGE_DETECTION              1403
#define IDC_EDGE_DETECTION_RANGE        1404
#define IDC_EDIT_TEXT                   1405
#define IDC_CHANGE_STATIC_TO_DYNAMIC    1406
#define IDC_EDGE_DETECTION_THRESHOLD    1407
#define IDC_CHANGE_DYNAMIC_TO_STATIC    1408
#define IDC_VIEW_EDGES                  1409
#define IDC_LOAD_FRAME                  1410
#define IDC_EDIT_CROSSHAIRS             1411
#define IDC_GENERATE_SCENE_FRAMEWORK    1412
#define IDC_IMPORT_LIST                 1413
#define IDC_SAVE_SESSION                1414
#define IDC_SHOW_LAYER_COLORS           1415
#define IDC_REPLACE_FRAME               1416
#define IDC_SHOW_MOUSEOVER_INFO         1417
#define IDC_SET_FIRST                   1418
#define IDC_LOAD_SESSION                1419
#define IDC_CULL_BACKFACES              1420
#define IDC_SET_LAST                    1421
#define IDC_VIEW_README                 1422
#define IDC_RENDER_BORDERS              1423
#define IDC_RENDER_LAYER_OUTLINES       1424
#define IDC_PLANAR_PROJECTION           1425
#define IDC_SET_HORIZONTAL_ROTATION     1426
#define IDC_RENDER_LAYER_MASK           1427
#define IDC_SAVE_CURRENT_ORIENTATION    1427
#define IDC_CONTOUR_EXTRUSION           1428
#define IDC_APPLY_SAVED_ORIENTATION     1428
#define IDC_ORIENT_VIEW_TO_GRID         1429
#define IDC_OPEN_DEPTH_SLIDER           1430
#define IDC_SET_VERTICAL_ROTATION       1431
#define IDC_IMPORT_ZDEPTH               1432
#define IDC_SET_Z_ROTATION              1432
#define IDC_OPEN_SCALE_SLIDER           1433
#define IDC_NEW_PROJECT                 1434
#define IDC_IMPORT_STEREO               1435
#define IDC_SET_HORIZONTAL_POSITION     1436
#define IDC_LOAD_PROJECT                1437
#define IDC_RENDER_NORMALS              1438
#define IDC_SAVE_PROJECT                1439
#define IDC_SET_VERTICAL_POSITION       1440
#define IDC_EXPORT_LAYERS               1441
#define IDC_RELIEF_MAP                  1442
#define IDC_SET_DEPTH_POSITION          1443
#define IDC_EXPORT_ZDEPTH               1444
#define IDC_PLAY_SEQUENCE               1445
#define IDC_HORIZONTAL_ROTATION_SLIDER  1446
#define IDC_VERTICAL_ROTATION_SLIDER    1447
#define IDC_EXPORT_OPTIONS              1448
#define IDC_Z_ROTATION_SLIDER           1448
#define IDC_VERTICAL_ROTATION           1449
#define IDC_IMPORT_OPTIONS              1450
#define IDC_Z_ROTATION                  1450
#define IDC_APPLY_TO_SELECTION          1451
#define IDC_BACKUP_CURRENT_CONTOURS     1452
#define IDC_CENTER_VIEW                 1453
#define IDC_BACKUP_ALL_CONTOURS         1454
#define IDC_USE_MANUAL_RASTERIZATION    1454
#define IDC_CENTER_VERTICAL_ROTATION    1455
#define IDC_CLEAR_TRACKING_INFO         1456
#define IDC_CENTER_Z_ROTATION           1456
#define IDC_CENTER_HORIZONTAL_POSITION  1457
#define IDC_EXTRA_SMOOTH_OUTLINES       1458
#define IDC_CENTER_VERTICAL_POSITION    1459
#define IDC_CENTER_DEPTH_POSITION       1460
#define IDC_CONTRACT_OUTLINES           1461
#define IDC_EXTRA_APPLY_POST_BLEND      1462
#define IDC_SET_PREVIEW_SKIP            1463
#define IDC_INCREASE_PREVIEW_SKIP       1464
#define IDC_DECREASE_PREVIEW_SKIP       1465
#define IDC_PREVIEW_SKIP                1466
#define IDC_DECREASE_EXTRUSION_ANGLE    1467
#define IDC_DIRECTIONAL_EXTRUSION_SLIDER 1468
#define IDC_RESET_STEREO                1469
#define IDC_RESET_EXTRUSION_ANGLE       1470
#define IDC_RESET_TO_SELECTION          1471
#define IDC_BIAS                        1472
#define IDC_RELIEF_IMAGE                1473
#define IDC_TILING_SLIDER               1474
#define IDC_PICK_CONVEX_COLOR           1475
#define IDC_FOV                         1476
#define IDC_SET_FOV                     1477
#define IDC_BACKGROUND_COLOR_BUTTON     1478
#define IDC_PROJECTION_SETTINGS         1479
#define IDC_DOME_PROJECTION             1480
#define IDC_CYLINDER_PROJECTION         1481
#define IDC_FLIP_REDBLUE                1482
#define IDC_ANAGLYPH_OUTPUT             1483
#define IDC_STEREO_OUTPUT               1484
#define IDC_LEFT_RIGHT_OUTPUT           1485
#define IDC_FILE_FORMAT                 1486
#define IDC_START_FRAME                 1487
#define IDC_OUTPUT_PATH                 1488
#define IDC_END_FRAME                   1489
#define IDC_BROWSE_OUTPUT_PATH          1490
#define IDC_FILE_PREFIX                 1491
#define IDC_UPDATE_CONTOURS             1492
#define IDC_USE_BACKUP_CONTOURS         1493
#define IDC_FULLSCREEN_APP              1494
#define IDC_FULL_SCREEN_APP             1495
#define IDC_TRACK_OUTLINE               1496
#define IDC_COLOR_SCHEME                1497
#define IDC_PREVIEW_TOOL                1498
#define IDC_COPY_EDITS_ALL_FRAMES       1499
#define IDC_COPY_EDITS_SINGLE_FRAME     1500
#define IDC_OPEN_VIRTUAL_CAMERA_TOOL    1501
#define IDC_PAINT_TOOL                  1502
#define IDC_PLUGINS                     1504
#define IDC_TOUCHUPS_TOOL               1505
#define IDC_HALO_TOOL                   1506
#define IDC_IMPORT_LAYER_EDITS          1507
#define IDC_HI_RES_PERFORMANCE          1508
#define IDC_EXPORT_BACKGROUND_MESH      1509
#define IDC_IMPORT_BACKGROUND_MESH      1510
#define IDC_EXPORT_LEFT_GAP_MASK        1511
#define IDC_EXPORT_RIGHT_GAP_MASK       1512

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        217
#define _APS_NEXT_COMMAND_VALUE         1513
#define _APS_NEXT_CONTROL_VALUE         1201
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
